---
- name: Check OS major version.
  ansible.builtin.assert:
    that:
      - 7 <= (ansible_facts.distribution_major_version | int)
      - (ansible_facts.distribution_major_version | int) <= 8
    fail_msg: "'ansible_facts.distribution_major_version' must be between 7 and 8"

- name: Download fish repo info
  become: true
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_{{ ansible_facts.distribution_major_version }}/shells:fish:release:3.repo"
    dest: /etc/yum.repos.d/
    mode: '0644'

- name: Install fish
  become: true
  ansible.builtin.yum:
    name: fish
