---
- name: Check OS major version.
  ansible.builtin.assert:
    that:
      - 9 <= (ansible_facts.distribution_major_version | int)
      - (ansible_facts.distribution_major_version | int) <= 12
    fail_msg: "'ansible_facts.distribution_major_version' must be between 9 and 12"

- name: Add source to source.list.d
  become: true
  ansible.builtin.copy:
    content: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_{{ ansible_facts.distribution_major_version }}/ /"
    dest: /etc/apt/sources.list.d/shells:fish:release:3.list
    mode: '0644'
    owner: root
    group: root

- name: Get stats of shells_fish_release_3.gpg file
  become: true
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg
  register: stat_result

- name: Download shells_fish_release_3.gpg
  when: not stat_result.stat.exists
  block:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir

    - name: Download Release.key
      ansible.builtin.get_url:
        url: "https://download.opensuse.org/repositories/shells:fish:release:3/Debian_{{ ansible_facts.distribution_major_version }}/Release.key"
        dest: "{{ tmpdir.path }}/Release.key"
        mode: "0644"

    - name: Read Release.key
      ansible.builtin.slurp:
        src: "{{ tmpdir.path }}/Release.key"
      register: release_key

    - name: Create gpg key file
      become: true
      ansible.builtin.command: gpg --dearmor
      args:
        stdin: "{{ release_key.content | b64decode }}"
      register: gpg_dearmor
      changed_when: true

    - name: Delete Release.key
      ansible.builtin.file:
        path: "{{ tmpdir.path }}/Release.key"
        state: absent

    - name: Add shells_fish_release_3.gpg to trusted.gpg.d
      become: true
      ansible.builtin.copy:
        content: "{{ gpg_dearmor.stdout }}"
        dest: /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg
        mode: '0644'
        owner: root
        group: root

    - name: Run apt update
      become: true
      ansible.builtin.apt:
        update_cache: true

- name: Install fish
  become: true
  ansible.builtin.apt:
    name: fish
