---
- name: Collect facts
  become: true
  ansible.builtin.setup:

- name: Install fish on Debian
  ansible.builtin.include_tasks:
    file: Debian.yml
  when:
    - ansible_facts.distribution == "Debian"

- name: Install fish on Ubuntu
  ansible.builtin.include_tasks:
    file: Ubuntu.yml
  when:
    - ansible_facts.distribution == "Ubuntu"

- name: Install fish on CentOS
  ansible.builtin.include_tasks:
    file: CentOS.yml
  when:
    - ansible_facts.distribution == "CentOS"

- name: Install fish on Rocky
  ansible.builtin.include_tasks:
    file: Rocky.yml
  when:
    - ansible_facts.distribution == "Rocky"
