---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
  - name: centos8stream
    image: quay.io/centos/centos:stream8
  - name: ubuntu_focal
    image: ubuntu:focal
  - name: ubuntu_jammy
    image: ubuntu:jammy
  - name: debian_buster
    image: debian:buster
  - name: debian_bullseye
    image: debian:bullseye
provisioner:
  name: ansible
  playbooks:
    prepare: ../playbooks/prepare.yml
verifier:
  name: ansible
