---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky9
    image: quay.io/ucomesdag/rocky:latest
    pre_build_image: true
  - name: almalinux9
    image: quay.io/ucomesdag/almalinux:latest
    pre_build_image: true
  - name: ubuntu_focal
    image: ubuntu:focal
  - name: ubuntu_jammy
    image: ubuntu:jammy
  - name: debian_buster
    image: debian:buster
  - name: debian_bullseye
    image: debian:bullseye
  - name: debian_bookworm
    image: debian:bookworm
provisioner:
  name: ansible
  playbooks:
    prepare: ../playbooks/prepare.yml
verifier:
  name: ansible
